name: Build

on:
  push:
    branches: ["main"]

jobs:
#  build:
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@v3
#      - name: Build with Node v20
#        uses: actions/setup-node@v3
#        with:
#          node-version: 20
#      - run: npm ci
#      - run: npm run build:ssr:prod
  deploy:
#    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/kevinpatrzek.fr/Portofolio
            git pull
            git status
            curl -sL https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh -o install_nvm.sh
            bash install_nvm.sh
            rm install_nvm.sh
            export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
              [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
            nvm install 20
            npm install pm2 -g
            npm install --yes
            npm run build:ssr:prod
            pm2 kill
            pm2 start dist/Portfolio/server/main.js
    